### ISSUE TITLE
Detect presence/absence of component in reel via CV to avoid chute jamming?

### ISSUE THREAD

**Issue by brainstorm** [markmaker/PushPullFeeder#10]
The nozzle tip computer vision pipeline in OpenPnP has a nice feature where the camera can detect if a nozzle tip is present or absent in the "holding rack" via empty vs occupied images: https://github.com/openpnp/openpnp/wiki/Nozzle-Tip-Changer#vision-calibration

I know that there are mechanisms such as vacuum sensing to tell if a component has been picked up or not successfully by the nozzle tip, but I was wondering if the pushpullfeeders could have the **vision** reliability checks to avoid mis-picks and subsequent jamming towards the chute?:

![IMG_2009](https://user-images.githubusercontent.com/175587/152797372-b39d34df-c721-4439-a691-d94e91f4570e.JPG)

OTOH, the feeder does not usually jam, but I guess that it might eventually jam given a big enough accumulation of components in some parts of the chute...

**Comment by brainstorm** [comment]
> But if you have that condition, what happens in bottom vision? Are these cases not caught by the missing parts?

Oddly enough, the bottom vision does recognize resistors (by the bounding rectangle drawn around), but when there's a miss-pick and the bare nozzle looks at the bottom camera, the Job continues as if everything was fine and it tries to place even when there's no resistor to be placed :/

/cc @PancakeLegend

**Comment by markmaker** [comment]
That's odd. It should definitely not happen. Pipeline?

**Comment by markmaker** [comment]
I think we agreed that the problem should be detected in the alignment, so I can close this here.
_Mark
