### ISSUE TITLE
Adjusting width of tape inset slot

### ISSUE THREAD

**Issue by infinitemachinery** [markmaker/PushPullFeeder#12]
The slot for the tape in the tape inset is too snug in width. Some of the 8mm tapes I have will not even fit. What would be the correct parameter to adjust to slightly increase the width in the inset? Tape_width is not the one, as that appears to only be for the standard sizes 8,12,16, etc.

**Comment by markmaker** [comment]
Hi @infinitemachinery

You're right, there isn't an actual parameter for that. It was never a problem so far, as the inset is one-sided and when pushing it to the body, I was able to make it a bit more or less tight. 

But I see the need and I'll add it.

_Mark

**Comment by markmaker** [comment]
See #13.
