### ISSUE TITLE
Add parameter for adjusting tension of the spool axle end clip

### ISSUE THREAD

**Issue by infinitemachinery** [markmaker/PushPullFeeder#15]
The little clip that can be used at the end of the cover spool axle has rather loose tension. Add a variable to adjust the depth of the notch that the clip is attached to.

![axle clamp](https://user-images.githubusercontent.com/71993878/204860018-308d9490-0bef-445b-a2d9-a2674af66ea1.png)

**Comment by markmaker** [comment]
Addressed by #16, thank you @infinitemachinery
