### ISSUE TITLE
Parts don't fit

### ISSUE THREAD

**Issue by tufelkinder** [markmaker/PushPullFeeder#17]
I exploded this into parts using the OpenSCAD and printed it on my Original Prusa and none of the parts fit together. I pounded a couple together to make them fit and ultimately they just broke off. What am I likely doing wrong...?

**Comment by markmaker** [comment]
Hi @tufelkinder 

Please watch the video:
https://youtu.be/cNCjjvCT4Fc

Especially the part about adjusting the play using the test print:
https://youtu.be/cNCjjvCT4Fc?t=78

This project makes it a _design goal_ not to require screws, springs etc. so everybody can just print it without ordering parts. But this only works if you adjust the play to your printer, filament and settings.

_>  ultimately they just broke off_

Just in case you missed this: this project was developed for PETG, it will certainly **not** work with PLA. 

See also here about the goals and features:
https://makr.zone/new-all-3d-printed-tapereel-feeder/399/


_Mark

**Comment by tufelkinder** [comment]
Thank you, hadn't seen this Youtube video previously, so that's obviously very helpful.

For what it's worth, they broke off under extreme pressure and strain to connect and move the pieces. Still, I can look at switching to PETG.

**Comment by markmaker** [comment]
I am closing this for now. If issues remain, we can always reopen it.
