### ISSUE TITLE
New LumenPNP Needs Notch

### ISSUE THREAD

**Issue by AmeNote-Michael** [markmaker/PushPullFeeder#18]
The new LumenPNP with their electronic feeders have added a backing positioning plate for their feeders to match their electronics. This adds requirement for a notch in the mount.

Love your PushPull Feeders. I am just tuning to use with my LumenPNP and look forward to having all my components on feeders. Strip feeders are just a pain and although I have a bunch of the LumenPNP feeders, I cannot afford for every component.

Could you add option for notch to support the new mounting of the LumenPNP. The image provided hopefully gives you all details needed for the notch. I am glad to test print and fit.

![BasePlateNotch](https://github.com/user-attachments/assets/c478e953-6310-49c4-99bf-4a27d5b23540)

**Comment by AmeNote-Michael** [comment]
By the way, the dimensions provided are in mm.

**Comment by AmeNote-Michael** [comment]
For overhang, you will likely need to print in supports that need to be cut out.

**Comment by AmeNote-Michael** [comment]
Just realized I could provide you the overall dimensions of the additional tabs on back of 2020 x member. It is 5mm deep by 5mm wide.

**Comment by markmaker** [comment]
See #19 for a combined answer.

_Mark

**Comment by markmaker** [comment]
See #19.
