### ISSUE TITLE
Lever does not position on build Plate when subtract from extrusion mount edge

### ISSUE THREAD

**Issue by AmeNote-Michael** [markmaker/PushPullFeeder#19]
To use LumenPNP existing extrusion mount, the extrusion mount edge y needs to be changed to -35. Doing so causes the default build plate print postion for the Lever to be inside the base part. Simple to fix by rendering seperately, but would be nice if can just generate.

<img width="787" alt="image" src="https://github.com/user-attachments/assets/057c5f8b-5f25-4141-8508-3cbb0678a554">

**Comment by markmaker** [comment]
Hi @AmeNote-Michael,

this answer includes #18.

Unfortunately, your -15mm adjustment of **extrusion mount edge y** is way more than I ever anticipated. As you see it also renders the tape chute cutout wrongly, i.e., it would be blocked like that we would need to improve from the simplistic way it is currently done. Maybe you don't want the chute at all, then we would need a way to disable it entirely, so it won't do the cutouts at all, and waste print time. 

Trying to reconstruct your case, I also have problems with the lock lever cutouts (cut in two). You somehow seem to have overcome this, by adjusting more params, right? I fear such large changes would require many test-prints and much tuning until everything is peachy again. I'm not saying it can't be done, but you would need to be ready to invest that kind of time, effort and filament.

Making the base so much larger will also increase your print time per feeder significantly. I spent an eternity making everything as small as possible to bring it down.

Furthermore, I doubt you'll make it still fit one standard print platter, which is an important design goal too. Maybe if you leave out the chute, but then the design is not really complete, i.e., while you might be happy with this, the next user might not (which taints this option in the "Open Source" spirit a bit).

Your #18 requirement adds more problems to these. Including, as you guessed, need for 3D printing supports, which were entirely avoided in the main design so far. Again much thinking went into how to achieve that.

With #18 you also force the feeders to align with the notches. I haven't found specs, but assume the feeder is quite wide if a 12mm option exists with the same notches. If the push-pull feeders are narrower at their < 16mm, you'll waste space, i.e., the number of feeders you can add. And you'll lose some stability. The feeders are thought to really snuggle close to each other to add stability and to dampen some vibrations.

All-in-all I'd like you to consider another option:

Seeing the Lumen has two feeder banks, you could dedicate one to PushPullFeeders, or even just a part of one. Then mount another 20x20 V-slot extrusion on top of the feeder rail. Just some holes through it and then [drop in tee nuts](https://openbuildspartstore.com/drop-in-tee-nuts-pack/) in the lower rail, and screw down (countersunk). 

This will even add to the stability of the frame. Vibrations from the push-pull actuation are a potential problem with 0402 parts, I needed to support my 20x20 extrusion every ~200mm for it to work all across.

Finally mount the mostly unmodified, proven PushPullFeeder on top. Given your -15mm Y adjustment, I assume you'll get a +5mm pick Z. This is not super-optimal, but still okay. With some careful tuning it could probably be reduced down a few millimeters.

You can always remove the extrusions on top, e.g. once you can afford more electric ones. With the drop in tee nuts, nothing is permanently modified or damaged on your machine.

What do you think?

_Mark

**Comment by AmeNote-Michael** [comment]
Mark, thanks for quick reply. I had considered your option and looked into getting the materials as you suggested. I was thinking the bounce might be an issue, but your suggestion of several t bolts is a good idea. Will look at that. I am planning to use rear feeder bar for electronic and front feeder bar for push pull. Leaves a small build plate though, especially with my version of LumenPNP. Going to look into if I can mod mine to the latest version from Lumen which mounts the air pumps and electronics on side.

I like the idea of having a mix of feeders, depending on project. Use the Lumen feeders for components that exist pretty much everywhere, but use the push pull for even components you may originally consider only in strip feeders.

Need to complete builds of a current job I have on device and then looking forward to experimenting. Using this time to print a bunch of feeders.

Will go with adding additional bar as you suggest.

Thanks.

**Comment by markmaker** [comment]
I'm closing this for now. We can always reopen, when needed.
