### ISSUE TITLE
friction_wings variable used instead of hex_face to build the spool left

### ISSUE THREAD

**Issue by uncle-buzz** [markmaker/PushPullFeeder#21]
I found an issue with the number of faces of the friction wheel and the spool left that uses the number of wings instead of the number of faces, so creating a friction wheel with 7 wings and 6 faces will build a spool left with 7 faces, I replace the friction_wheel variable with the hex_face at line 3018 and the build is now conform, sorry I don"t know how to propose a PR :
`                   union() {
                        translate([0, 0, -e]) {
                            beveled_extrude(height=spool_wall_left+2*e, bevel=bevel_z, angle=135) {
                                circle_p(d=friction_hex_diameter,
                                    $fn=hex_face);
                            }
                        }
                    }`
instead of 
`                   union() {
                        translate([0, 0, -e]) {
                            beveled_extrude(height=spool_wall_left+2*e, bevel=bevel_z, angle=135) {
                                circle_p(d=friction_hex_diameter,
                                    $fn=friction_wings);
                            }
                        }
                    }`

**Comment by markmaker** [comment]
Hi @uncle-buzz,

> so creating a friction wheel with 7 wings and 6 faces will build a spool left with 7 faces.

I was unable to reproduce that. Both are built with 7 faces. As far [as I see in the code](https://github.com/search?q=repo%3Amarkmaker%2FPushPullFeeder%20%24fn%3Dfriction_wings&type=code), the matching part also has the `$fn=friction_wings` shape. This also shows in the preview:

![hexnut](https://github.com/user-attachments/assets/5caf1bf5-2fb0-459f-901d-0b233b0242b8)

Of course, if you change the parameter **friction wings**, you need to _reprint_ the **spool left** to match it.

![make options](https://github.com/user-attachments/assets/e9649c13-3200-46a1-883a-1347dd991fc2)

I agree it is a bit confusing to still call this "friction_hex" in the code when it is no longer hexagonal once you change the number of wings. And having to reprint the  **spool left** is also not optimal. 

So I would accept  PR that changes it _everywhere_ (also needs to be changed in the `friction_hex_diameter` calculation). Are you sure you can't learn how? It is a liberating feeling to be able to contribute :rocket: :smile: 

_Mark

**Comment by uncle-buzz** [comment]
My bad, checking the code on GitHub shows there is no hex_faces variable in your file, I probably added it to add wings without changing the number of faces and forgot to use this new variable for the spool left...
The bug exists only in my files because I created it. Sorry
I dealt with it a few months ago, but I have forgotten it...
