### ISSUE TITLE
One of the 3D printed pieces is not used for anything?

### ISSUE THREAD

**Issue by brainstorm** [markmaker/PushPullFeeder#4]
In the GIF animation from the README.md, the piece circled in red in this issue seemingly serves no purpose? Can you elaborate why it was (is?) used for?:

<img width="713" alt="Screen Shot 2021-07-05 at 4 02 02 pm" src="https://user-images.githubusercontent.com/175587/124424591-9b9f0180-ddaa-11eb-93d8-1c11ef13b205.png">

We were quite puzzled while putting the pieces together XD

/cc @cpgmoore

**Comment by markmaker** [comment]
Hi @brainstorm 

That's not normally used. I just added it to support the full EIA 481 standard. According to the standard, the reel (the hub) can be very wide. It seems they were often made from thick cardboard in the past. If the full EIA 481 width of the reel is used, then that counter nut and hanger thingy (image below) does not fit into the feeder slot width I wanted not to exceed. 

![grafik](https://user-images.githubusercontent.com/9963310/124433143-b190d000-dd72-11eb-9877-c27ab0336140.png)

You then have to rely on the reel being held on one side only and the next feeder keeping it from falling off. In that case, there is nothing holding the spent tape spool. **Then this little part comes into play.** 

I frankly don't expect to encounter many reels that use the full width. But they do seem to exist, see here:

https://groups.google.com/g/openpnp/c/y1X3I8l31vM/m/DZQb2gLvAQAJ

_Mark

**Comment by brainstorm** [comment]
Epic response, thanks Mark, good to know if we encounter those ;)
