### ISSUE TITLE
Adding more wings to the friction wheel affects spool fitting?

### ISSUE THREAD

**Issue by brainstorm** [markmaker/PushPullFeeder#9]
The orange wheel has more edges than the simple hexagon of the first two blue and red friction wheels:

![IMG_2008](https://user-images.githubusercontent.com/175587/152789993-3b2650a8-a676-4ddc-b4cb-2b4f7d4f789a.JPG)

Therefore the previously printed spools do not have an optimal fit... although they coincidentally work fine, I just wanted to report this since I think it's a bug... the nut that locks with the spool should be an hexagon, independently of the number of wings from the friction wheel, IMHO.

In other words, adding more wings to the wheel would make the wheel-to-spool interface more unreliable since it'd eventually converge towards a circumference which could slip... keeping the hexagon shape irrespective of the number of wings would help.

Also, spoiler, the latter one is the difference of getting our feeders to work properly without retractions or not. The amount of wings on the orange piece is the one that makes our feeders work the most consistently with 0603 component reels.

![IMG_2012](https://user-images.githubusercontent.com/175587/152799453-a1662dd6-8563-465c-a989-44fb66ce0a83.JPG)

**Comment by markmaker** [comment]
Just also wanted to add that I'm well aware that the reliability of the friction wheel is the Achilles heel of the whole feeder. Each filament change required me to adapt its settings. I always managed to get it working, but it is definitely not "print and forget". 

Anything to make it better is highly welcome. 👍👍👍

**Comment by brainstorm** [comment]
I'll try to carve out some time and fix this hexagon issue, but it's actually not too critical, the wheel holds in place fine for now because the tolerances are good enough (for the testing we've been conducting so far and the use they've seen).

@PancakeLegend was theorizing on using magnets instead, but I'm not exactly sure how that'd work plus it introduces non-3D printed parts, which is not as practical as a fully 3D printed feeder.

OTOH a redesign/version of this feeder for laser cutting would be amazing because it'd cut down the manufacturing time greatly, but I massively digress here X"D
